### ISSUE TITLE
Whether "convertView.getTag() == null" is necessary ?

### ISSUE THREAD

**Issue by zhanggao** [MinimalBible/MinimalBible#23]
### Your code is

if (convertView == null || convertView.getTag() == null) {
     xxxxxx
} else {
     xxxxxx
}
### Why not just

if (convertView == null) {
     xxxxxx
} else {
     xxxxxx
}

**Comment by bspeice** [comment]
I'd appreciate a specific reference to help dig into this more, but this is a null-safe lookup: I actually want to know if `convertView.getTag()` is `null`, but to make it safe to call `getTag()` I need to first check if the `convertView` is null.

Closing as this isn't an issue, but a question. Feel free to keep asking.
